In [4]:
import numpy as np

# 1D array

a = np.array([1,2,3,4,5])
print(a)
print(a.ndim)
print(a.shape)

[1 2 3 4 5]
1
(5,)


In [6]:
arr2 = np.array([[1, 2, 3],
                 [4, 5, 6]])
print(arr2)
print(arr2.ndim)
print(arr2.shape)

[[1 2 3]
 [4 5 6]]
2
(2, 3)


In [7]:
# 3D Array
arr3 = np.array([[[1, 2], [3, 4]],
                 [[5, 6], [7, 8]]])
print(arr3)
print(arr3.ndim)
print(arr3.shape)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
3
(2, 2, 2)


In [8]:
# zero array
arr_zero = np.zeros((3,3))
print(arr_zero)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [9]:
# array of ones with shape (2,5)
ones_arr = np.ones((2,5))
print(ones_arr)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [10]:
# array filed with 7
seven_arr = np.full((2,3), 7)
print(seven_arr)

[[7 7 7]
 [7 7 7]]


In [11]:
# Create an array of even numbers between 10 and 50 using arange.
even_arr = np.arange(10, 51, 2)
print(even_arr)


[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]


In [12]:
# Create a 4×4 matrix from 0–15

matrix = np.arange(16).reshape(4,4)
print(matrix)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [13]:
# first row
first_row = matrix[0]
print(first_row)

[0 1 2 3]


In [14]:
# the last column
last_column = matrix[:, -1]
print(last_column)

[ 3  7 11 15]


In [16]:
# Extract a 2x2 subarray from the center
center_subarray = matrix[1:3,1:3]
print(center_subarray)

[[ 5  6]
 [ 9 10]]


In [17]:
arr = np.array([1,2,3])
mat = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])
result = mat + arr
print(result)

[[ 2  4  6]
 [ 5  7  9]
 [ 8 10 12]]


In [22]:
A = np.array([1,2,3,4])
B = np.array([5,6,7,8])

result1 = (A + B)
result2 = (A + B) / 2
print(result1)
print(result2)

squared_sum = A**2 + B**2
print(squared_sum)

[ 6  8 10 12]
[3. 4. 5. 6.]
[26 40 58 80]
